### ISSUE TITLE
Endre AAREG og EREG tjenester

### ISSUE THREAD

**Issue by KnutArildSlaatsve** [navikt/medlemskap-oppslag#559]
Heisann!

På vegne av Team Arbeidsforhold ønsker vi at dere går over til å benytte nais-versjonene av AAREG og EREG

Info om aareg(-services) finner dere [her](https://github.com/navikt/aareg-services)
Info om ereg(-services) finner dere [her](https://github.com/navikt/ereg-services)

Alt fungerer som før - vi er bare på nye ingresser.

Aareg-services har støtte for TokenX/AzureAD om dere vil benytte dere av det og er tilgjengelig fra GCP via pub ingress

Dersom dere bruker SOAP-Tjenester så blir vi veldig glade dersom dere går over til REST (gjelder aareg)

**Comment by hjmNav** [comment]
Takk for oppretting av issue :) Vi ser på det asap !

**Comment by StianSDouzette** [comment]
Vi har nå gått over til nye URLer for aareg og eereg, lukker derfor denne.
